### PR TITLE
Update clinicaltrials_download to use tframe with NULL query

### PR DESCRIPTION
**Pull request by titaniumtroop**
I was getting the “No query parameters given” error when trying to use
a tframe to download CT.gov results. The first if statement in the code
triggers the error because the tframe argument isn’t taken into
account. I restructured the main if-else block to build the appropriate
query given either a query or tframe. Tested successfully with a tframe
and query, both with a NULL count and count = 90.

### CODE REVIEW

**Comment by sachsmc** [comment]
Thanks! Could you add your test to https://github.com/sachsmc/rclinicaltrials/blob/master/tests/testthat/test-download.R ?

Maybe something less than count = 90, so it doesn't take too long to run.

**Comment by titaniumtroop** [comment]
I added two commits. One is to include the test code for the tframe-based download you requested.

The other commit implements downloading for count > 100 tframe-based downloads. The test case shows the intended usage of selecting just complete trials for download.

**Comment by sachsmc** [comment]
@titaniumtroop 

thank-you-dog-graphic

**Comment by titaniumtroop** [comment]
You're welcome. Thanks for writing a helpful package.

**Pull request merged**
